name: Github action demo
on: push
jobs:
  action-demo:
   runs-on: ubuntu-latest
   steps:
     - name: checkout the code
       uses: actions/checkout@v4
       # run: echo "a demo build"
     - name: print index
       run: cat index.html
       # run: echo "Hey,${{secrets.DOCKER_PASS}}"
      

